# Generated by Django 3.0.7 on 2020-06-14 14:38

import django.core.validators
from django.db import migrations, models
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0003_auto_20200611_1142'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='telephone',
            new_name='msisdn',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='telephone_verified',
            new_name='msisdn_verified',
        ),
        migrations.RenameField(
            model_name='otpcode',
            old_name='telephone',
            new_name='msisdn',
        ),
        migrations.AlterField(
            model_name='otpcode',
            name='identifier',
            field=models.SlugField(choices=[('email_validation', 'Email Validation'), ('msisdn_validation', 'Telephone Validation'), ('register_validation', 'Register Validation'), ('password_reset_validation', 'Password Reset Validation'), ('change_msisdn_validation', 'Change Telephone Validation'), ('change_email_validation', 'Change Email Validation'), ('change_username_validation', 'Change Username Validation'), ('change_password_validation', 'Change Password Validation')], max_length=128, null=True, validators=[django.core.validators.RegexValidator(message="Code can only contain the letters a-z, A-Z, digits, and underscores, and can't start with a digit.", regex='^[a-zA-Z_][0-9a-zA-Z_]*$'), utils.validators.non_python_keyword]),
        ),
    ]
