# Generated by Django 3.0.7 on 2020-06-14 23:42

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import utils.validators
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('person', '0004_auto_20200614_2138'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPFactory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('msisdn', models.CharField(blank=True, max_length=14, null=True)),
                ('token', models.CharField(max_length=64)),
                ('passcode', models.CharField(max_length=10)),
                ('valid_until', models.DateTimeField(blank=True, editable=False, null=True)),
                ('attempt_allowed', models.IntegerField(default=3)),
                ('attempt_used', models.IntegerField(default=0)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_used', models.BooleanField(default=False)),
                ('is_expired', models.BooleanField(default=False)),
                ('identifier', models.SlugField(choices=[('email_validation', 'Email Validation'), ('msisdn_validation', 'Telephone Validation'), ('register_validation', 'Register Validation'), ('password_reset_validation', 'Password Reset Validation'), ('change_msisdn_validation', 'Change Telephone Validation'), ('change_email_validation', 'Change Email Validation'), ('change_username_validation', 'Change Username Validation'), ('change_password_validation', 'Change Password Validation')], max_length=128, null=True, validators=[django.core.validators.RegexValidator(message="Code can only contain the letters a-z, A-Z, digits, and underscores, and can't start with a digit.", regex='^[a-zA-Z_][0-9a-zA-Z_]*$'), utils.validators.non_python_keyword])),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='otps', related_query_name='otp', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'OTP Factory',
                'verbose_name_plural': 'OTP Factories',
                'db_table': 'person_otp_factory',
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='OTPCode',
        ),
    ]
