# Generated by Django 3.0.7 on 2020-06-15 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0007_auto_20200615_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpfactory',
            name='valid_until_timestamp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
